const FOLLOW_PAGE_LIMIT = 50;
const MOVIE_PAGE_LIMIT = 10;

const SHRT_LENGTH = 60;
const MEDM_LENGTH = 110;
const LONG_LENGTH = 111;


module.exports = {FOLLOW_PAGE_LIMIT, MOVIE_PAGE_LIMIT, SHRT_LENGTH, MEDM_LENGTH, LONG_LENGTH}


