INSERT INTO genres (mid, genre) VALUES
(1, 'Animation'),
(1, 'Adventure'),
(1, 'Comedy'),
(1, 'Family'),
(1, 'Fantasy'),
(2, 'Adventure'),
(2, 'Family'),
(2, 'Science Fiction'),
(3, 'Animation'),
(3, 'Adventure'),
(3, 'Comedy'),
(3, 'Family'),
(3, 'Fantasy'),
(3, 'Science Fiction'),
(4, 'Animation'),
(4, 'Adventure'),
(4, 'Comedy'),
(4, 'Family'),
(5, 'Animation'),
(5, 'Action'),
(5, 'Adventure'),
(5, 'Family');