INSERT INTO movie_cast (mid, name, role, character) VALUES
(1, 'John Lasseter', 'Director', '72'),
(1, 'John Lasseter', 'Writer', '72'),
(1, 'Pete Docter', 'Writer', '72'),
(1, 'Andrew Stanton', 'Writer', '72'),
(1, 'Tom Hanks', 'Actor', 'Woody'),
(1, 'Tim Allen', 'Actor', 'Buzz Lightyear'),
(1, 'Don Rickles', 'Actor', 'Mr. Potato Head'),
(2, 'Steven Spielberg', 'Director', '72'),
(2, 'Melissa Mathison', 'Writer', '72'),
(2, 'Dee Wallace', 'Actor', 'Mary'),
(2, 'Henry Thomas', 'Actor', 'Elliot'),
(3, 'Phil Lord', 'Director', '72'),
(3, 'Christopher Miller', 'Director', '72'),
(3, 'Phil Lord', 'Writer', '72'),
(3, 'Christopher Miller', 'Writer', '72'),
(3, 'Bill Lader', 'Actor', 'Flint Lockwood'),
(3, 'Anna Faris', 'Actor', 'Sam Sparks'),
(3, 'James Caan', 'Actor', 'Tim Lockwood'),
(4, 'John Lasseter', 'Director', '72'),
(4, 'Joe Ranft', 'Director', '72'),
(4, 'John Lasseter', 'Writer', '72'),
(4, 'Joe Ranft', 'Writer', '72'),
(4, 'Jorgen Klubien', 'Writer', '72'),
(4, 'Owen Wilson', 'Actor', 'Lightning McQueen'),
(4, 'Paul Newman', 'Actor', 'Doc Hudson'),
(4, 'Bonnie Hunt', 'Actor', 'Sally Carrera'),
(5, 'Brad Bird', 'Director', '72'),
(5, 'Brad Bird', 'Writer', '72'),
(5, 'Craig T. Nelson', 'Actor', 'Bob Parr'),
(5, 'Holly Hunter', 'Actor', 'Helen Parr'),
(5, 'Sarah Vowell', 'Actor', 'Violet Parr'),
(5, 'Spencer Fox', 'Actor', 'Dash Parr'),
(5, 'Eli Fucile', 'Actor', 'Jack-Jack Parr');