CREATE TABLE Rating (
uID INTEGER NOT NULL REFERENCES Users(uID),
mID INTEGER NOT NULL REFERENCES Movies(mID),
score INT NOT NULL,
ratingText VARCHAR(255),
upvotes INT,
downvotes INT,
t_stamp TIME NOT NULL,
PRIMARY KEY(uID, mID)
);