CREATE TABLE User (
    uID SERIAL NOT NULL PRIMARY KEY,
    f_name NOT NULL VARCHAR(255),
    l_name NOT NULL VARCHAR(255),
    username NOT NULL VARCHAR(255),
    email NOT NULL VARCHAR(255),
    password NOT NULL VARCHAR(255)
);
